### PR TITLE
feature(OcAgentExpoter): Allow to setup the service name from a window variable.

### PR DESCRIPTION
**Pull request by Blightwidow**
Please refer to #155 for more context.

### CODE REVIEW

**Comment by Blightwidow** [comment]
@googlebot I signed it!

**Comment by draffensperger** [comment]
@googlebot please recheck the CLA!

**Comment by draffensperger** [comment]
After I get this merged I will also do another release

**Comment by Blightwidow** [comment]
Great so it will solve the npm issue right ?

**Comment by draffensperger** [comment]
Yes, it should. I'm not sure why the CLA bot seems to be moving slowly. I'll see if I can find anything else about it.

**Comment by draffensperger** [comment]
Regarding the CLA, is it possible that your commit doesn't have an email address associated with it, or the email your using isn't tied to your GitHub account? See https://opensource.google.com/docs/cla/#troubleshoot

**Comment by draffensperger** [comment]
(It's also possible the CLA bot is just running slowly. I'll check back later today on it if it doesn't resolve soon as I have a number of meetings today)

**Comment by Blightwidow** [comment]
@googlebot I signed it!

Just updated it

**Pull request merged**
